### ISSUE TITLE
springboot2 版本什么时候出？

### ISSUE THREAD

**Issue by iamzxj** [jeesun/oauthserver#4]

**Comment by jeesun** [comment]
如果可能的话，我周末会抽时间更新到Spring Boot2。

**Comment by iamzxj** [comment]
3Q3Q😀😀😀

**Comment by jeesun** [comment]
暂时已经把Spring Boot版本从1.5.14.RELEASE升级到2.0.3.RELEASE，还没来得及更新文档，所以我commit在develop分支。
