### ISSUE TITLE
使用阿里的仓库编译报错  提示jasypt-spring-boot-starter 2.0.0下不下来   使用1.14版本的成功变异，有影响么？

### ISSUE THREAD

**Issue by itapril** [jeesun/oauthserver#5]

**Comment by jeesun** [comment]
查看jasypt-spring-boot-starter的[文档](https://github.com/ulisesbocchio/jasypt-spring-boot)可以知道，2.0.0版本是针对Spring Boot 2做的升级。
原文内容：Update 3/17/2018: Version 2.0.0 has been released supporting Spring Boot 2.0.X.RELEASE.
你可以选择在[maven官方仓库](http://mvnrepository.com)直接下载jar并放到本地仓库，地址[jasypt-spring-boot-starter/2.0.0](http://central.maven.org/maven2/com/github/ulisesbocchio/jasypt-spring-boot-starter/2.0.0/)。

**Comment by itapril** [comment]
谢谢回复~~
![image](https://user-images.githubusercontent.com/16377373/42792525-41f5566a-89a8-11e8-81ef-b8abbceb5f22.png)
还是报错

**Comment by jeesun** [comment]
jasypt-spring-boot-starter1.x和2.x在application.yml中的配置是没有变化的，至少目前是这样。所以使用1.x也可以。你这个截图中的，还是jar下载不到的问题。
