### ISSUE TITLE
无法获取token

### ISSUE THREAD

**Issue by 511098425** [jeesun/oauthserver#6]
是用sql脚本提供的用户名和密码会提示警告，并且返回的额是 401 Unauthorized

**Comment by jeesun** [comment]
你使用的是1.x还是2.x

**Comment by 511098425** [comment]
2.x呀

**Comment by 511098425** [comment]
我从master上面拉取的，看版本是2.x

**Comment by 511098425** [comment]
我自己写貌似也遇到了这种问题，一样的错误

**Comment by jeesun** [comment]
oauthserver从v1.x升级到v2.x，需要修改数据表oauth_client_details的clicent_secret列的值，从明文secret改为经过Scrypt加密的字符串$2a$11$uBcjOC6qWFpxkQJtPyMhPOweH.8gP3Ig1mt27mGDpBncR7gErOuF6。

**Comment by 511098425** [comment]
好像是这个问题，现在可以了

**Comment by 511098425** [comment]
现在只支持password模式？后续有没有实现auth_code模式和client模式

**Comment by jeesun** [comment]
暂时只支持password模式。
